services:
  fastapi:
    build: .
    container_name: office-ai-mate-api
    restart: unless-stopped
    environment:
      - DEFAULT_PROVIDER=OpenRouter
      - DEFAULT_MODEL=arcee-ai/trinity-large-preview:free
      - DEFAULT_API_KEY="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"
    volumes:
      - ./data:/app/data

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: office-ai-mate-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
